### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by pizzav-xyz** [Ynfuien/YnfuBot#2]
how run on linux because linux doesnt have bat files

**Comment by Ynfuien** [comment]
Bat file just runs an npm command - `npm run dev:watch`. So you can type it yourself in a terminal in the project's directory or create a .sh file with it

**Comment by pizzav-xyz** [comment]
> Bat file just runs an npm command - `npm run dev:watch`. So you can type it yourself in a terminal in the project's directory or create a .sh file with it

then it says this 

npm run dev:watch

> mineflayer-chat-bot@2.2.1 dev:watch
> nodemon src/index.js

sh: line 1: nodemon: command not found

**Comment by Ynfuien** [comment]
Did you install npm packages first with `npm install`? Also alternatively you can use `npm run dev` instead of `dev:watch`

**Comment by pizzav-xyz** [comment]
> Did you install npm packages first with `npm install`? Also alternatively you can use `npm run dev` instead of `dev:watch`

[2024-06-04T20_03_56_836Z-debug-0.log](https://github.com/user-attachments/files/15569798/2024-06-04T20_03_56_836Z-debug-0.log)

**Comment by Ynfuien** [comment]
```
[...]
794 info run better-sqlite3@9.6.0 install node_modules/better-sqlite3 prebuild-install || node-gyp rebuild --release
795 info run better-sqlite3@9.6.0 install { code: 1, signal: null }
796 verbose stack Error: command failed
[...]
806 error gyp info spawn args [
806 error gyp info spawn args '/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
806 error gyp info spawn args 'binding.gyp',
806 error gyp info spawn args '-f',
806 error gyp info spawn args 'make',
806 error gyp info spawn args '-I',
806 error gyp info spawn args '/home/pizzav/Documents/MineflayerChatBot/node_modules/better-sqlite3/build/config.gypi',
806 error gyp info spawn args '-I',
806 error gyp info spawn args '/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
806 error gyp info spawn args '-I',
806 error gyp info spawn args '/home/pizzav/.cache/node-gyp/22.2.0/include/node/common.gypi',
806 error gyp info spawn args '-Dlibrary=shared_library',
806 error gyp info spawn args '-Dvisibility=default',
806 error gyp info spawn args '-Dnode_root_dir=/home/pizzav/.cache/node-gyp/22.2.0',
806 error gyp info spawn args '-Dnode_gyp_dir=/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp',
806 error gyp info spawn args '-Dnode_lib_file=/home/pizzav/.cache/node-gyp/22.2.0/<(target_arch)/node.lib',
806 error gyp info spawn args '-Dmodule_root_dir=/home/pizzav/Documents/MineflayerChatBot/node_modules/better-sqlite3',
806 error gyp info spawn args '-Dnode_engine=v8',
806 error gyp info spawn args '--depth=.',
806 error gyp info spawn args '--no-parallel',
806 error gyp info spawn args '--generator-output',
806 error gyp info spawn args 'build',
806 error gyp info spawn args '-Goutput_dir=.'
806 error gyp info spawn args ]
806 error gyp ERR! build error 
806 error gyp ERR! stack Error: not found: make
806 error gyp ERR! stack at getNotFoundError
[...]
```

It looks like better-sqlite can't be build. Probably because of this `Error: not found: make`. Try `apt install make` and then install npm packages

**Comment by pizzav-xyz** [comment]
I don't have apt

**Comment by Ynfuien** [comment]
Then use whatever alternative you have to install `make`

**Comment by pizzav-xyz** [comment]
I'll try when I'm home

**Comment by pizzav-xyz** [comment]
[2024-06-05T12_57_51_374Z-debug-0.log](https://github.com/user-attachments/files/15587269/2024-06-05T12_57_51_374Z-debug-0.log)

**Comment by Ynfuien** [comment]
Yeah, I don't know. It works for me on Windows 10 and on two different Ubuntu 22.04.4 machines, there is no errors while installing better-sqlite3. It's not a MineflayerChatBot issue but rather something with your setup. You should try reading the errors and googling for solutions. Also you might try installing latest sqlite package `npm i better-sqlite3@11`, since MCB has an older version in package.json
